# For the general syntax of property based configuration files see the
# documenation of org.apache.log4j.PropertyConfigurator.

# log4j properties file
log4j.appender.fileout=org.apache.log4j.DailyRollingFileAppender
log4j.appender.fileout.File = logs/simulator.log
log4j.appender.fileout.layout=org.apache.log4j.PatternLayout
log4j.appender.fileout.layout.ConversionPattern=%5p --> %d [%t] (%F:%L) - %m%n
log4j.appender.fileout.DatePattern='.'yyyyMMdd

log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.Target=System.out
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=%5p --> %d [%t] (%F:%L) - %m%n

# Catch-all logger: file + console (all log information on console)
log4j.rootLogger=INFO, fileout, console
#log4j.logger.deng=INFO
